Scarso327/AltisLife-Framework

- Client Side/Framework/Functions/Tablet/Messaging/fn_messages.sqf
> fix: messages while viewing inbox stacking event handler

- Client Side/Framework/Functions/Events/fn_addEachFrame.sqf
- Client Side/Framework/Functions/Events/fn_onEachFrame.sqf
- Client Side/Framework/Functions/Hints/fn_hint.sqf
- Client Side/Framework/Functions/Hints/fn_hintEachFrame.sqf
- Client Side/Framework/Functions/Initialisation/fn_preInitVars.sqf
fixes
Some help with the altis life #441
> fix: each frame handlers being removed prematurely breaking things like hints

- Client Side/Framework/Functions/Prison/CfgPrison.hpp
- Client Side/Framework/Functions/Prison/fn_imprison.sqf
- Client Side/Framework/Functions/Spawn/fn_spawnMenu.sqf
fixes Some help with the altis life #441
> fix: prison spawn + resimprison on death

- Client Side/Framework/Functions/Housing/fn_buyHouse.sqf
fixes Buying a house you cannot afford will soft lock it if you later get enough money until you relog #455
> fix: buying a house you cannot afford soft locking it

- Client Side/Framework/CfgFunctions.hpp
- Client Side/Framework/Functions/Tablet/CfgTablet.hpp
- Client Side/Framework/Functions/Tablet/Inventory/fn_bpLbChange.sqf
- Client Side/Framework/Functions/Tablet/Inventory/fn_invLbChange.sqf
- Client Side/Framework/Functions/Tablet/Inventory/fn_licenses.sqf
- Client Side/Framework/UI/DialogTablet/Screens/Inventory.hpp
- Client Side/Framework/UI/Functions/fn_setToTextHeight.sqf
fixes Crafting display doesn't indicate if the workbench is required or not #459
> fix: workbench requirement not showing in tablet

- Client Side/Framework/Functions/Stores/Clothing/CfgClothesStore.hpp
fixes Syntax error when opening police clothing store #457
> fix: syntax error when opening police clothing store

- Client Side/Framework/Functions/Events/fn_InventoryClosed.sqf
- Client Side/Framework/Functions/Events/fn_onKilled.sqf
- Client Side/Framework/UI/DialogInventory/DialogInventory.hpp
- Server Side/life_server/Functions/Database/Player/fn_savePlayerInfo.sqf
- Server Side/life_server/Functions/Database/Player/fn_savePlayerState.sqf
- Server Side/life_server/Functions/Player/fn_registerSession.sqf
- Server Side/life_server/Functions/Player/fn_unregisterSession.sqf
fixes Some help with the altis life #441
> fix: item dupe through poor gear syncing

- Client Side/Framework/Functions/Crafting/fn_nearWorkbench.sqf
> fix: workbenchNear check

- Client Side/Framework/Functions/Tablet/Messaging/fn_messages.sqf
> fix: send button getting stuck if you view a message you can't reply to

- Client Side/Framework/Functions/Tablet/Inventory/fn_bpLbChange.sqf
> fix: workbench ui check

- Server Side/life_server/Functions/Database/Group/fn_createGroup.sqf
> fix: sql error on group creation where inactive record exists

- Client Side/Framework/Functions/Freight/fn_claimFreight.sqf
- Client Side/Framework/Functions/Missions/CfgMissions.hpp
> fix: freight missions

- Client Side/Framework/CfgFunctions.hpp
- Client Side/Framework/Functions/Freight/fn_claimFreight.sqf
- Client Side/Framework/Functions/Freight/fn_onEachFrameFreight.sqf
- Client Side/Framework/Functions/Missions/CfgMissions.hpp
- Client Side/Framework/Functions/Selects/fn_selectObject.sqf
> fix: freight missions not failing on mission store

- Client Side/Framework/CfgFunctions.hpp
- Client Side/Framework/Functions/Achievements/fn_initAchievements.sqf
- Client Side/Framework/Functions/Events/fn_onEnterRadiatedZone.sqf
- Client Side/Framework/Functions/Events/fn_onLeftRadiatedZone.sqf
- Client Side/Framework/Functions/Initialisation/fn_initEventHandlers.sqf
> feat(radiation): added damage effect to radiation

- Client Side/Framework/Functions/Inventory/fn_giveItem.sqf
- Client Side/Framework/Functions/Inventory/fn_giveVirtualItems.sqf
- Client Side/Framework/Functions/Inventory/fn_recieveItem.sqf
- Client Side/Framework/Functions/Selects/fn_selectObject.sqf
- Client Side/Framework/Functions/VirtualInventory/fn_openInventory.sqf
- Client Side/Framework/Functions/VirtualInventory/fn_putInCargo.sqf
- Client Side/Framework/Functions/VirtualInventory/fn_takeFromCargo.sqf
fixes You are unable to give scripted items #399
> fix(vitems): giving / storing scripted items

- Client Side/Framework/Functions/Admin/fn_checkPower.sqf
> fix(admin): check power null reference

- Client Side/Framework/CfgDebriefing.hpp
- Client Side/Framework/Functions/Database/Player/fn_getPlayerInfo.sqf
- Client Side/Framework/Functions/Database/Player/fn_setPlayerInfo.sqf
- Client Side/Framework/Functions/Spawn/fn_spawnMenu.sqf
- Server Side/life_server/Functions/Database/Player/fn_queryPlayerInfo.sqf
> fix: being able to respawn to bypass player query

- Server Side/life_server/Functions/Database/Player/fn_queryPlayerInfo.sqf
> fix: error on create new players

- Client Side/Framework/Functions/Vehicle/CfgVehicles.hpp
- Client Side/Framework/Functions/Vehicle/fn_initVehicle.sqf
- README.md
> feat(vehicles): increased fuel consumption

- Client Side/Framework/Functions/Markers/fn_initMarkers.sqf
> fix: map markers being drawn on top of each other

- Client Side/Framework/Functions/Group/fn_initGroups.sqf
> fix: group tags not updating on join

- Client Side/Framework/Functions/Group/CfgGroups.hpp
- Client Side/Framework/Functions/Group/fn_initGroups.sqf
- Server Side/life_server/Functions/Database/Group/fn_addGroupXP.sqf
> feat(groups): xp for corporate groups when selling legal event items

- Server Side/life_server/Functions/Bases/fn_initBases.sqf
- Server Side/life_server/Functions/Cartels/fn_cartelReward.sqf
- Server Side/life_server/Functions/Database/Government/fn_handleVotes.sqf
> fix: incorrect usage of log player event

- Client Side/Framework/Functions/Input/fn_keyDown.sqf
- Client Side/Framework/Functions/Vehicle/CfgVehicles.hpp
> fix: sirens on helis + light error when no position set

- Client Side/Framework/Functions/Goals/CfgGoals.hpp
> alter: police daily goal to be more achievable

- Client Side/Framework/Functions/Mail/fn_claimMail.sqf
> fix(mail): virtual item max quantity calc

- Client Side/Framework/Functions/Garage/fn_populateGarage.sqf
- Client Side/Framework/Functions/Items/fn_itemCfg.sqf
- Client Side/Framework/Functions/Stores/fn_addCart.sqf
- Client Side/Framework/Functions/Stores/fn_loadSavedCart.sqf
- Client Side/Framework/Functions/Stores/fn_switchCategory.sqf
- Client Side/Framework/Functions/Vehicle/fn_vehicleCfg.sqf
- Client Side/Framework/Functions/VehicleStore/fn_vehicleStore.sqf
> feat: dlc icons to stores

- Client Side/Framework/Functions/Events/fn_onEachFrame.sqf
- Client Side/Framework/Functions/Events/fn_onGetIn.sqf
- Client Side/Framework/Functions/Options/CfgOptions.hpp
> feat: setting to automatically switch veh channel

- Client Side/Framework/Functions/Tablet/Group/fn_changeTax.sqf
- Server Side/life_server/Functions/Database/Group/fn_queryGroupInfo.sqf
- Server Side/life_server/Functions/Database/Group/fn_setGroupTax.sqf
> fix: group tax not saving

- Client Side/Framework/Configuration/CfgSettings.hpp
- Client Side/Framework/Functions/Events/fn_onDamaged.sqf
> feat: greenzone damage protection

- Client Side/Framework/Functions/Interactions/CfgInteractions.hpp
> fix(vehicle): police reg check requires toolkit

- Client Side/Framework/Functions/Interactions/CfgInteractions.hpp
> fix: obselete check vitem option

- Client Side/Framework/Functions/Initialisation/fn_initPlayer.sqf
- Client Side/Framework/Functions/Player/fn_canHeal.sqf
> fix: treat person appearing for people in cars

- Server Side/life_server/Functions/Events/fn_onPlayerKilled.sqf
> fix: police taking rep damage for killing armed civs

- Client Side/Framework/Functions/VirtualInventory/fn_openInventory.sqf
> fix: restrained player's inventory accessible by people not in restrainer's grroup

- Client Side/Framework/CfgFunctions.hpp
- Client Side/Framework/Functions/Events/fn_onGetIn.sqf
- Client Side/Framework/Functions/Events/fn_onGetOut.sqf
- Client Side/Framework/Functions/Initialisation/fn_initEventHandlers.sqf
- Client Side/Framework/Functions/Initialisation/fn_initialisation.sqf
- Client Side/Framework/Functions/Options/CfgOptions.hpp
- Client Side/Framework/Functions/Options/fn_setViewDistance.sqf
> feat: view distance settings

- Client Side/Framework/Configuration/CfgSettings.hpp
- Server Side/life_server/CfgFunctions.hpp
- Server Side/life_server/Functions/Weather/fn_handleFog.sqf
- Server Side/life_server/fn_init.sqf
> feat: basic system to stop excessive fog

- Client Side/Framework/Functions/Garage/fn_retrieveGarage.sqf
> fix: accessing vehicles in garage you don't meet requirements for

- Client Side/Framework/Functions/Items/CfgVirtualItems.hpp
> alter: drug buy prices to rebalance purified being created from buying the base product

- Client Side/Framework/Functions/Inventory/fn_recieveItem.sqf
> fix: being able to give someone infinite item weight

- Client Side/Framework/Functions/VirtualInventory/fn_openInventory.sqf
> fix: accessing vehicle inventory if someone is inside it

- Client Side/Framework/Configuration/CfgSettings.hpp
- Client Side/Framework/Functions/Events/fn_onDamaged.sqf
- Client Side/Framework/Functions/Events/fn_onFired.sqf
- Client Side/Framework/Functions/Events/fn_onKnocked.sqf
- Client Side/Framework/Functions/Events/fn_onReloaded.sqf
- Client Side/Framework/Functions/Items/Types/Primary.hpp
- Client Side/Framework/Functions/Items/Types/Secondary.hpp
> feat: better rubbers

- Client Side/Framework/Functions/Achievements/CfgAchievements.hpp
- Client Side/Framework/Functions/Spawn/CfgSpawns.hpp
- Client Side/Framework/Functions/Titles/CfgTitles.hpp
Added ATM to prison market and gang base vehicle stores Added Sofia and Agios Clinics (Inc medic spawn points) Added patrol missions to all clinics
Added medical supply stores to clinics
Added 8 robbable fuel stations
Added ladder to turtle dealer
Added redzone to blackmarket
Added 3 mystery achievements (Inc titles)
Fixed "Mile High" achievement altitude
Fixed equipment box in Agios Police Station
Fixed spawn in prison
Fixed date of map to shorten night
Fixed jewlery store sign positioning
> Requested Map Changes, Additional Mystery Achievements and Titles

- Server Side/life_server/Functions/Events/fn_initEvents.sqf
- Server Side/life_server/Functions/Events/fn_onPlayerKilled.sqf
Reverts Scarso327/AltisLife-Framework#615
> Revert "fix: death messages for exploding cars"
